version: '3.8'
services:
    laravel:
        build:
            context: ./
            dockerfile: ./laravel/Dockerfile
        container_name: nasavasa-ru-laravel
        restart: unless-stopped
        tty: true
        #ports:
        #    - '80:80'
        hostname: nasavasa-ru
        networks:
            - nginx_net
            - laravel-postgres_net
        depends_on:
            - postgres
    postgres:
        image: 'postgres:15'
        container_name: nasavasa-ru-postgres
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - nasavasa.ru_database:/var/lib/postgresql/data
        networks:
            - laravel-postgres_net
networks:
    laravel-postgres_net:
        driver: bridge
    nginx_net:
        driver: bridge
        external: true
volumes:
    nasavasa.ru_database:
